# ====================
# 🟦 BLUE Deployment
# ====================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      version: blue
  template:
    metadata:
      labels:
        app: myapp
        version: blue
    spec:
      containers:
        - name: myapp
          image: nginx:1.21
          ports:
            - containerPort: 80
---
# ====================
# ✅ GREEN Deployment
# ====================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      version: green
  template:
    metadata:
      labels:
        app: myapp
        version: green
    spec:
      containers:
        - name: myapp
          image: nginx:1.25
          ports:
            - containerPort: 80
---
# ====================
# 🔁 Service (initially points to GREEN)
# ====================
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
    version: green  # ⬅️ এখানে switchable
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
